name: widget_with_codeview
description: A widget with side-by-side source code view.
version: 1.0.5
homepage: https://github.com/X-Wei/widget_with_codeview

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_floatactionbuttons: ^0.1.0
  google_fonts: ^1.1.1
  string_scanner: ^1.0.5
  url_launcher: ^5.7.10
  admob_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: